### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Ankit0080** [varunrramani/MaterialProgressBar#1]
This code is not working with Apptheme  so i added the theme of this code and now setcontent view is not calling inside activity. No Progressbar at all do you have any solution about that.? i have tried but this code is no progressbar is  showing only it dims the activity background. if you want i will give you the code

**Comment by varunrramani** [comment]
Hi Ankit, I have stopped working on this project. For a solution you can may be contact the original creator of the project. This was just a fork of the project which I made to make my use case work. http://takeoffandroid.com/uncategorized/material-progress-dialog-using-v4-support-library/ this is the tutorial which the original creator had posted.
